
guacamole:
  image:
    repository: docker.io/guacamole/guacamole
    pullPolicy: IfNotPresent
    # Default is the chart appVersion.
    tag: ""
  replicaCount: 1
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  # guacamole.properties
  properties: {}
  # Kubernetes env
  env: []
  # Kubernetes envFrom
  envFrom: []
  # Dict of secret environment variables
  secretEnv: {}
  # https://guacamole.apache.org/doc/gug/json-auth.html#configuring-guacamole-to-accept-encrypted-json
  jsonSecretKey:

service:
  type: ClusterIP
  port: 8080

guacd:
  image:
    repository: docker.io/guacamole/guacd
    pullPolicy: IfNotPresent
    # Default is the chart appVersion.
    tag: ""
  replicaCount: 1
  podAnnotations: {}
  podLabels: {}
  podSecurityContext: {}
  securityContext: {}
  resources: {}
  nodeSelector: {}
  tolerations: []
  affinity: {}
  service:
    type: ClusterIP
    port: 4822

imagePullSecrets: []

# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  # Automatically mount a ServiceAccount's API credentials?
  automount: false
  annotations: {}
  name: ""

ingress:
  enabled: false
  className: ""
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local
