apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guacamole.fullname" . }}-guacd
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: guacd
spec:
  replicas: {{ .Values.guacd.replicaCount }}
  selector:
    matchLabels:
      {{- include "guacamole.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: guacd
  template:
    metadata:
      {{- with .Values.guacd.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "guacamole.labels" . | nindent 8 }}
        app.kubernetes.io/component: guacd
        {{- with .Values.guacd.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "guacamole.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.guacd.podSecurityContext | nindent 8 }}
      containers:
        - name: guacd
          securityContext:
            {{- toYaml .Values.guacd.securityContext | nindent 12 }}
          image: "{{ .Values.guacd.image.repository }}:{{ .Values.guacd.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.guacd.image.pullPolicy }}
          ports:
            - name: guacd
              containerPort: 4822
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 4822
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            tcpSocket:
              port: 4822
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            {{- toYaml .Values.guacd.resources | nindent 12 }}
      {{- with .Values.guacd.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.guacd.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.guacd.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
