apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "guacamole.fullname" . }}
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: guacamole
spec:
  replicas: {{ .Values.guacamole.replicaCount }}
  selector:
    matchLabels:
      {{- include "guacamole.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: guacamole
  template:
    metadata:
      {{- with .Values.guacamole.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "guacamole.labels" . | nindent 8 }}
        app.kubernetes.io/component: guacamole
        {{- with .Values.guacamole.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "guacamole.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.guacamole.podSecurityContext | nindent 8 }}
      containers:
        - name: guacamole
          securityContext:
            {{- toYaml .Values.guacamole.securityContext | nindent 12 }}
          image: "{{ .Values.guacamole.image.repository }}:{{ .Values.guacamole.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.guacamole.image.pullPolicy }}
          env:
            - name: GUACAMOLE_HOME
              value: /etc/guacamole
            - name: GUACD_HOSTNAME
              value: {{ include "guacamole.fullname" . }}-guacd
            - name: LOGBACK_LEVEL
              value: debug
          envFrom:
            - secretRef:
                name: {{ include "guacamole.fullname" . }}-env
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /guacamole/
              port: http
          readinessProbe:
            httpGet:
              path: /guacamole/
              port: http
          resources:
            {{- toYaml .Values.guacamole.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/guacamole/guacamole.properties
              subPath: guacamole.properties
      volumes:
        - name: config
          configMap:
            name: {{ include "guacamole.fullname" . }}
      {{- with .Values.guacamole.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.guacamole.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.guacamole.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
