apiVersion: v1
kind: Secret
metadata:
  name: {{ include "guacamole.fullname" . }}-env
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $k,$v := .Values.guacamole.secretEnv }}
    {{ $k }}: {{ $v | b64enc }}
  {{- end }}
