apiVersion: v1
kind: Service
metadata:
  name: {{ include "guacamole.fullname" . }}-guacd
  labels:
    {{- include "guacamole.labels" . | nindent 4 }}
    app.kubernetes.io/component: guacd
spec:
  type: {{ .Values.guacd.service.type }}
  ports:
    - port: {{ .Values.guacd.service.port }}
      targetPort: 4822
      protocol: TCP
      name: guacd
  selector:
    {{- include "guacamole.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: guacd
