name: Build
on:
  push:
  pull_request:

env:
  CHART_NAME: guacamole
  COMMIT_USER: manics-bot
  VALIDATE_KUBERNETES_VERSION: "1.30.6"

jobs:

  helmchart:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubeconform
        run: curl -sfL https://github.com/yannh/kubeconform/releases/download/v0.7.0/kubeconform-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - kubeconform

      - name: Lint
        run: |
          helm lint helm-chart/
          helm template helm-chart/ | kubeconform -strict -verbose -kubernetes-version "$VALIDATE_KUBERNETES_VERSION"

      - name: Update Chart.yaml version with tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          yq eval --inplace ".version |= \"${{ github.ref_name }}\"" helm-chart/Chart.yaml
          git diff

      - name: Build chart
        run: |
          helm package helm-chart

      - uses: jupyterhub/action-k3s-helm@v4
        with:
          k3s-channel: v1.31

      - name: Install chart
        run: helm install guac ./helm-chart --wait

      - name: Test chart
        run: helm test guac

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Add chart to gh-pages
        run: |
          shopt -s nullglob
          filename=(${CHART_NAME}-*.tgz)
          if [ -z "$filename" ]; then
            echo "No chart found"
            exit 1
          fi
          if [ -f "gh-pages/$filename" ]; then
            echo "Chart $filename already exists"
            exit 1
          fi
          mv "$filename" gh-pages/
          helm repo index gh-pages/

      - name: Commit gh-pages
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          git config user.name "$COMMIT_USER"
          git config user.email "${COMMIT_USER}@users.noreply.github.com"
          git add --all
          git commit -m "Update chart"
        working-directory: gh-pages

      - name: Push gh-pages
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          git push origin gh-pages
        working-directory: gh-pages
